// Sync
export const MAKE_SELECTED_PROJECT = 'MAKE_SELECTED_PROJECT';
export const MAKE_SELECTED_MUSIC = 'MAKE_SELECTED_MUSIC';

// Async
export const FETCH_SITE_TEXT_REQUESTED = 'FETCH_SITE_TEXT_REQUESTED';
export const FETCH_SITE_TEXT_SUCCEEDED = 'FETCH_SITE_TEXT_SUCCEEDED';
export const FETCH_SITE_TEXT_FAILED = 'FETCH_SITE_TEXT_FAILED';

export const FETCH_PROJECTS_REQUESTED = 'FETCH_PROJECTS_REQUESTED';
export const FETCH_PROJECTS_SUCCEEDED = 'FETCH_PROJECTS_SUCCEEDED';
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED';

export const FETCH_MUSICS_REQUESTED = 'FETCH_MUSICS_REQUESTED';
export const FETCH_MUSICS_SUCCEEDED = 'FETCH_MUSICS_SUCCEEDED';
export const FETCH_MUSICS_FAILED = 'FETCH_MUSICS_FAILED';
